CCIP fee fix
glacislabs/v1-core pull request #5
Opened 2024-03-09 13:21 UTC by gusjavaz

Additionally this PR:

Replaces XERC20 extension with GXT (GlacisCrossChainToken)
Adds counterpart support to GXT
Swaps constructor arguments on LZ Adapter to follow the rest of the adapters approach
Force retriable to true when sendind tokens
Replaces setAdapterChain on CCIP adapter to  setGlacisChainIds to follow the rest of the adapters approach

2024-03-11 18:01 UTC, jboetticher requested changes
Don't have much of an issue with enforcing the remote counterpart interface within the Glacis XERC20. Main issue is with the retry functionality change.

I think we should really approach Jacob & any other potential users of XERC20 with the question about enforcing the counterpart manager. Especially the tradeoff:

1. Counterpart is stored within the GXT: XERC20s must have either the GXT interface or the same address value, otherwise Glacis cannot bridge your token.
2. Counterpart is stored within the token router: all XERC20s with just the base token can be transferred, but addresses are centralized.

We can always replace/upgrade the token router later to include functionality 2 once we have correct governance protocols in place.

2024-03-11 18:01 UTC, jboetticher commented on contracts/mediators/GlacisTokenMediator.sol
> +        bool, // retriable
If we are keeping this as true always, then the interface should be reflected as such and this parameter should be removed

2024-03-13 16:59 UTC, gusjavaz commented on contracts/mediators/GlacisTokenMediator.sol
> +        bool, // retriable
You are right. Changed.

2024-03-13 17:08 UTC, gusjavaz commented
> w
There is a third option which is to have a cross chain token registry like LZ. After reviewing all the options, my opinion is that Glacis should implement an xERC20 address registry, since we should not let Glacis rely completely on the issuer, since the issuer could change the token variant at any time. I guess for now we should only rely on a permissioned Glacis Cross Chain Token Registry where glacis labs had control of the token counterparts. I have modified the PR to reflect this proposal. What do you think?

2024-03-13 17:11 UTC, gusjavaz commented
I've also added a Dockerfile so we can both work in a common container.

2024-03-13 18:02 UTC, jboetticher requested changes
I can't approve this architecture if we haven't addressed the governance issue. XERC20 is supposed to give the developer more freedom and control, but if we gatekeep who can set which tokens correspond to which addresses and/or give ourselves an easy backdoor then it defeats the purpose.

Perhaps there is an architecture that sets the registry as the "last resort" instead of a requirement?

2024-03-13 18:02 UTC, jboetticher commented on contracts/token/GlacisCrossChainTokenRegistry.sol
> +    ) external override onlyOwner {
How do people permissionlessly deploy cross-chain tokens if this functionality is limited to just the owner?

2024-03-13 18:07 UTC, jboetticher commented
> cross chain token registry like LZ

I didn't know LZ had that, I thought that each OFT had to register their own token variants. But I'm certain that Wormhole had this originally with their token attestation. 

> the issuer could change the token variant at any time. 

If they want to do that, then they should have the ability to do so. Perhaps they are migrating to a new version of their token.

2024-03-13 18:42 UTC, gusjavaz commented on contracts/token/GlacisCrossChainTokenRegistry.sol
> +    ) external override onlyOwner {
The token deployment is permissionless but the register in Glacis is by Glacis Governance

2024-03-13 18:50 UTC, gusjavaz commented
> > cross chain token registry like LZ
> 
> I didn't know LZ had that, I thought that each OFT had to register their own token variants. But I'm certain that Wormhole had this originally with their token attestation.
> 
> > the issuer could change the token variant at any time.
> 
> If they want to do that, then they should have the ability to do so. Perhaps they are migrating to a new version of their token.

The Token attestation service 

> > cross chain token registry like LZ
> 
> I didn't know LZ had that, I thought that each OFT had to register their own token variants. But I'm certain that Wormhole had this originally with their token attestation.
> 
> > the issuer could change the token variant at any time.
> 
> If they want to do that, then they should have the ability to do so. Perhaps they are migrating to a new version of their token.

How Glacis could deal with a malicious issuer that changes the token counterpart after setting limits for Glacis?

2024-03-13 18:55 UTC, jboetticher commented on contracts/token/GlacisCrossChainTokenRegistry.sol
> +    ) external override onlyOwner {
Deployment is permissionless but we control when & if you can use your deployment? Sounds like the same thing to me :)

2024-03-13 18:55 UTC, jboetticher commented
> How Glacis could deal with a malicious issuer that changes the token counterpart after setting limits for Glacis?

I'm not sure what the attack is that you're talking about here. Could you expand?

2024-03-13 19:20 UTC, gusjavaz commented
> > How Glacis could deal with a malicious issuer that changes the token counterpart after setting limits for Glacis?
> 
> I'm not sure what the attack is that you're talking about here. Could you expand?

I'll create a separate PR for the token counterpart since it is not related to these fixes. There we can discuss the best approach.

2024-03-14 13:45 UTC, gusjavaz commented
Removed from this PR

1. Replaces XERC20 extension with GXT (GlacisCrossChainToken)
2. Adds counterpart support to GXT

2024-03-14 14:17 UTC, jboetticher approved these changes

2024-03-14 14:17 UTC, jboetticher commented on test/LocalTestSetup.sol
>              address(router),
Will have to make change to deployment too

2024-03-14 16:01 UTC, merged